# Header
menu:
  主页: /
  所有文章: /archives/
  关于: /about/
  # About: /about/

# SubNav
subnav:
  github: "https://github.com/lancezhange"
  weibo: "http://www.weibo.com/lancezhange"
#   zhihu: "#"
  #douban: "#"
  #mail: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: read more
fancybox: true
mathjax: true

# Miscellaneous
google_analytics: ''
favicon: /favicon.png

#你的头像url
avatar: http://pic.yupoo.com/lancezhange_v/DDabJ4ls/ip4iY.png
#是否开启分享
share: true
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: true
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
friends:
  Yihui: "http://yihui.name/en/"
  # 卡卡的美丽传说: http://localhost:4000/
  # 本泽马的博客: http://localhost:4000/
  # 吉格斯的博客: http://localhost:4000/
  # 习大大大不同: http://localhost:4000/
  # 托蒂的博客: http://localhost:4000/

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: false