language: node_js
node_js:
  - lts/*

before_install:
  - export TZ='Asia/Shanghai'

install:
  - npm install hexo-cli -g
  - npm install

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "lancezhange"
  - git config user.email "lancezhange@gmail.com"
  - git add .
  - git commit -m "Travis CI Auto Builder at $(date +'%Y-%m-%d %H:%M:%S')"
  - git push --force --quiet "https://${GITHUB_TOKEN}@github.com/lancezhage/lancezhange.github.io.git" master:master

cache:
  directories:
    - node_modules

branches:
  only:
    - master
