language: node_js
node_js:
  - lts/*

install:
  - npm cache verify
  - npm install hexo-cli -g
  - npm install

script:
  - npm run hexo-deploy

cache:
  directories:
    - node_modules

branches:
  only:
    - master
